version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: matjar
      POSTGRES_PASSWORD: matjar_pass
      POSTGRES_DB: matjar_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://matjar:matjar_pass@db:5432/matjar_db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data: